services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db
    depends_on:
      - mongo
    restart: unless-stopped

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data:
